[profile.default]
src = "src"
out = "out"
libs = ["lib"]


# [profile.release]
optimizer = true
optimize_runs = 2000
via_ir = true

remappings = ["@chainlink/contracts/src/=lib/chainlink-brownie-contracts/contracts/src/", "@solmate=lib/solmate/src"]
# remappings = ["@chainlink/contracts/src/v0.8/shared/interfaces/ = /lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/"]

fs_permissions = [{ access = "read", path = "./broadcast" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
